use "Data.dta", clear




//Rename
rename  Nindnme Sector
rename Nnindcd Industy_Code
rename Ind Covered
rename region ETS

//drop
drop Indcd


//Translate province
replace province = "Shanghai" if province=="上海"
replace province = "Yunnan Province" if province=="云南省"
replace province = "Beijing" if province=="北京"
replace province = "Jilin Province" if province=="吉林省"
replace province = "Sichuan Province" if province=="四川省"
replace province = "Tianjin" if province=="天津"
replace province = "Anhui Province" if province=="安徽省"
replace province = "Shandong Province" if province=="山东省"
replace province = "Shanxi Province" if province=="山西省"
replace province = "Guangdong Province" if province=="广东省"
replace province = "Guangxi Zhuang Autonomous Region" if province=="广西壮族自治区"
replace province = "Xinjiang Uygur Autonomous Region" if province=="新疆维吾尔自治区"
replace province = "Jiangsu Province" if province=="江苏省"
replace province = "Jiangxi Province" if province=="江西省"
replace province = "Hebei Province" if province=="河北省"
replace province = "Henan Province" if province=="河南省"
replace province = "Zhejiang Province" if province=="浙江省"
replace province = "Hainan" if province=="海南省"
replace province = "Hubei Province" if province=="湖北省"
replace province = "Hunan Province" if province=="湖南省"
replace province = "Gansu province" if province=="甘肃省"
replace province = "Fujian Province" if province=="福建省"
replace province = "Tibet Autonomous Region" if province=="西藏自治区"
replace province = "Guizhou Province" if province=="贵州省"
replace province = "Liaoning Province" if province=="辽宁省"
replace province = "Chongqing" if province=="重庆"
replace province = "Shaanxi Province" if province=="陕西省"
replace province = "Heilongjiang Province" if province=="黑龙江省"
replace province = "Inner Mongolia Autonomous Region" if province=="内蒙古自治区"
replace province = "Qinghai Province" if province=="青海省"
replace province = "Ningxia Hui Autonomous Region" if province=="宁夏回族自治区"





//Translate Sector
replace Sector = "Hotel Sector" if Sector=="旅馆业"
replace Sector =" Other manufacturing"  if Sector=="其他制造业"
replace Sector ="Crude Oil Processing Sector " if Sector=="原油加工业"
replace Sector = "Household electronic appliance manufacturing Sector " if Sector=="日用电子器具制造业"
replace Sector ="Chemical preparation manufacturing "  if Sector=="化学药品制剂制造业"
replace Sector =" Chemical fertilizer manufacturing"  if Sector=="化学肥料制造业"
replace Sector ="Special equipment manufacturing Sector for metallurgy, mining and electromechanical industries "  if Sector=="冶金、矿山、机电工业专用设备制造业"
replace Sector =" Cotton Textile Sector"  if Sector=="棉纺织业"
replace Sector ="Miscellaneous"   if Sector=="综合类"
replace Sector =" Automotive Manufacturing"  if Sector=="汽车制造业"
replace Sector ="Transmission and distribution and control equipment manufacturing Sector"  if Sector=="输配电及控制设备制造业"
replace Sector =" Cement manufacturing"  if Sector=="水泥制造业"
replace Sector ="Chemical raw medicine manufacturing "  if Sector=="化学药品原药制造业"
replace Sector ="General equipment manufacturing "  if Sector=="通用设备制造业"
replace Sector ="Plastic board, tube and bar manufacturing "  if Sector=="塑料板、管、棒材制造业"
replace Sector ="Metal processing machinery manufacturing "  if Sector=="金属加工机械制造业"
replace Sector ="Electronic device manufacturing "  if Sector=="电子器件制造业"
replace Sector =" Household electrical appliance manufacturing"  if Sector=="日用电器制造业"
replace Sector =" Synthetic fiber manufacturing"  if Sector=="合成纤维制造业"
replace Sector ="Urban public transportation "  if Sector=="市内公共交通业"
replace Sector ="Heavy non-ferrous metal mining and dressing Sector "  if Sector=="重有色金属矿采选业"
replace Sector =" Paper Sector"  if Sector=="造纸业"
replace Sector =" Real estate development and operation Sector"  if Sector=="房地产开发与经营业"
replace Sector ="Plastic Manufacturing "  if Sector=="塑料制造业"
replace Sector ="Synthetic material manufacturing "  if Sector=="合成材料制造业"
replace Sector ="Biopharmaceutical Manufacturing"  if Sector=="生物药品制造业"
replace Sector =" Daily chemical product manufacturing"  if Sector=="日用化学产品制造业"
replace Sector ="Chemical pesticide manufacturing "  if Sector=="化学农药制造业"
replace Sector ="Slaughter and meat and egg processing Sector "  if Sector=="屠宰及肉类蛋类加工业"
replace Sector =" Electricity Production Sector"  if Sector=="电力生产业"
replace Sector =" Chinese herbal medicine and Chinese patent medicine processing Sector"  if Sector=="中药材及中成药加工业"
replace Sector =" Lighting equipment manufacturing Sector"  if Sector=="照明器具制造业"
replace Sector ="Communication equipment manufacturing Sector "  if Sector=="通信设备制造业"
replace Sector ="Coal mining Sector "  if Sector=="煤炭开采业"
replace Sector ="Alcohol and Beverage Wine Manufacturing "  if Sector=="酒精及饮料酒制造业"
replace Sector =" Motorcycle Manufacturing"  if Sector=="摩托车制造业"
replace Sector =" Other communication services"  if Sector=="其他通信服务业"
replace Sector ="Tire manufacturing "  if Sector=="轮胎制造业"
replace Sector ="Pharmaceutical and medical device retail "  if Sector=="药品及医疗器械零售业"
replace Sector ="Bearing and valve manufacturing "  if Sector=="轴承、阀门制造业"
replace Sector =" Precious metal mining and dressing Sector"  if Sector=="贵金属矿采选业"
replace Sector =" Other textile Sector"  if Sector=="其他纺织品业"
replace Sector ="Light non-ferrous metal smelting Sector "  if Sector=="轻有色金属冶炼业"
replace Sector ="Other special equipment manufacturing "  if Sector=="其他专用设备制造业"
replace Sector ="Transportation equipment manufacturing "  if Sector=="交通运输设备制造业"
replace Sector ="Steel rolling processing Sector "  if Sector=="钢压延加工业"
replace Sector ="Heavy non-ferrous metal smelting Sector "  if Sector=="重有色金属冶炼业"
replace Sector ="Basic chemical raw material manufacturing "  if Sector=="基本化学原料制造业"
replace Sector ="Electronic component manufacturing"  if Sector=="电子元件制造业"
replace Sector ="Petroleum Products Sector"  if Sector=="石油制品业"
replace Sector ="Vegetable oil processing Sector "  if Sector=="植物油加工业"
replace Sector ="Iron ore mining and dressing Sector "  if Sector=="铁矿采选业"
replace Sector ="Non-ferrous metal alloy Sector "  if Sector=="有色金属合金业"
replace Sector ="Plastic packaging box and container manufacturing "  if Sector=="塑料包装箱及容器制造业"
replace Sector ="Other biological products Sector "  if Sector=="其他生物制品业"
replace Sector ="forestry "  if Sector=="林业"
replace Sector =" Special equipment manufacturing Sector for light and textile Sector"  if Sector=="轻纺工业专用设备制造业"
replace Sector = "Gas supply Sector " if Sector=="煤气供应业"
replace Sector ="General merchandise retail "  if Sector=="日用百货零售业"
replace Sector ="General Instrument and Meter Manufacturing "  if Sector=="通用仪器仪表制造业"
replace Sector =" Computer network development, maintenance and consulting"  if Sector=="计算机网络开发、维护与咨询"
replace Sector ="Computer software development and consulting "  if Sector=="计算机软件开发与咨询"
replace Sector ="Electricity Supply Sector "  if Sector=="电力供应业"
replace Sector ="Other information dissemination services "  if Sector=="其他信息传播服务"
replace Sector ="Production and supply of steam and hot water "  if Sector=="蒸汽、热水的生产和供应业"
replace Sector ="Rare  earth metal mining and dressing Sector "  if Sector=="稀有稀土金属矿采选业"
replace Sector ="Food and feed processing Sector "  if Sector=="粮食及饲料加工业"
replace Sector ="Steelmaking Sector "  if Sector=="炼钢业"
replace Sector ="Other food manufacturing "  if Sector=="其他食品制造业"
replace Sector ="Coking Sector "  if Sector=="炼焦业"
replace Sector ="Aerospace Vehicle Manufacturing "  if Sector=="航空航天器制造业"
replace Sector ="Other ferrous metal mining and dressing Sector "  if Sector=="其他黑色金属矿采选业"
replace Sector ="Cast iron pipe manufacturing"  if Sector=="铸铁管制造业"
replace Sector ="Wool Textile Sector "  if Sector=="毛纺织业"
replace Sector ="Coal mining and dressing Sector "  if Sector=="煤炭采选业"
replace Sector ="Brick, lime and light construction material manufacturing"  if Sector=="砖瓦、石灰和轻质建筑材料制造业"
replace Sector ="Metal structure manufacturing "  if Sector=="金属结构制造业"
replace Sector ="Other non-metallic mineral products Sector "  if Sector=="其他非金属矿物制品业"
replace Sector ="Broadcasting and Television Equipment Manufacturing "  if Sector=="广播电视设备制造业"
replace Sector = "Knitwear Sector " if Sector=="针织品业"
replace Sector = "Printing Sector " if Sector=="印刷业"
replace Sector = "Soft drink manufacturing " if Sector=="软饮料制造业"
replace Sector = "Petrochemical and other industrial special equipment manufacturing " if Sector=="石化及其他工业专用设备制造业"
replace Sector =" Fermentation manufacturing"  if Sector=="发酵制造业"
replace Sector = "Other agriculture " if Sector=="其他农业"
replace Sector = "Boiler and prime mover manufacturing " if Sector=="锅炉及原动机制造业"
replace Sector = "Rubber parts manufacturing " if Sector=="橡胶零件制造业"
replace Sector = "Metal wire rope and its products Sector " if Sector=="金属丝绳及其制品业"
replace Sector = "Special instrument and meter manufacturing Sector " if Sector=="专用仪器仪表制造业"
replace Sector = " Clothing manufacturing" if Sector=="服装制造业"
replace Sector = "Wood-based panel manufacturing " if Sector=="人造板制造业"
replace Sector = "Sugar Sector " if Sector=="制糖业"
replace Sector ="Railway transportation equipment manufacturing Sector "  if Sector=="铁路运输设备制造业"
replace Sector = "Other fiber products manufacturing " if Sector=="其他纤维制品制造业"
replace Sector = "Rare  earth metal smelting Sector " if Sector=="稀有稀土金属冶炼业"
replace Sector ="Other electrical machinery manufacturing "  if Sector=="其他电器机械制造业"
replace Sector ="Coal washing Sector "  if Sector=="煤炭洗选业"
replace Sector ="Other metal products Sector "  if Sector=="其他金属制品业"
replace Sector = "Other processing industries " if Sector=="其他加工业"
replace Sector = "Other public facilities service Sector " if Sector=="其他公共设施服务业"
replace Sector ="Computer-related equipment manufacturing "  if Sector=="计算机相关设备制造业"
replace Sector = " Organic chemical product manufacturing" if Sector=="有机化学产品制造业"
replace Sector ="Other electronic equipment manufacturing "  if Sector=="其他电子设备制造业"
replace Sector = "Plastic film manufacturing " if Sector=="塑料薄膜制造业"
replace Sector = " Primary processing Sector of fiber raw materials" if Sector=="纤维原料初步加工业"
replace Sector = "Airport and air transportation auxiliary Sector " if Sector=="机场及航空运输辅助业"
replace Sector = "Tool manufacturing " if Sector=="工具制造业"
replace Sector = " Specialty Chemical Product Manufacturing" if Sector=="专用化学产品制造业"
replace Sector = "Refractory products Sector " if Sector=="耐火材料制品业"
replace Sector =" Paper products Sector"  if Sector=="纸制品业"
replace Sector = "Computer Application Service Sector " if Sector=="计算机应用服务业"
replace Sector = "Glass and glass products Sector " if Sector=="玻璃及玻璃制品业"
replace Sector = "Non-ferrous metal rolling processing Sector " if Sector=="有色金属压延加工业"
replace Sector = "Casting manufacturing " if Sector=="铸件制造业"
replace Sector = "Ceramic products Sector " if Sector=="陶瓷制品业"
replace Sector ="Stationery Manufacturing "  if Sector=="文化用品制造业"
replace Sector = " Other general parts manufacturing" if Sector=="其他通用零部件制造业"
replace Sector = " Motor Manufacturing" if Sector=="电机制造业"
replace Sector = "Other computer application services " if Sector=="其他计算机应用服务业"
replace Sector = "Special equipment manufacturing Sector " if Sector=="专用设备制造业"
replace Sector = "Mineral fiber and its products Sector " if Sector=="矿物纤维及其制品业"
replace Sector = "Cement products and asbestos cement products Sector " if Sector=="水泥制品和石棉水泥制品业"
replace Sector = "Oil and gas extraction service Sector " if Sector=="石油和天然气开采服务业"
replace Sector = "Confectionery and confectionery manufacturing " if Sector=="糕点、糖果制造业"
replace Sector ="Aquatic Products Processing Sector "  if Sector=="水产品加工业"
replace Sector =" Medical device manufacturing"  if Sector=="医疗器械制造业"
replace Sector ="Rubber sheet, tube and belt manufacturing "  if Sector=="橡胶板、管、带制造业"
replace Sector = " Precious metal smelting Sector" if Sector=="贵金属冶炼业"
replace Sector = "Biological Products Sector " if Sector=="生物制品业"
replace Sector = "Wholesale of medicines and medical equipment " if Sector=="药品及医疗器械批发业"
replace Sector = "Retail of textiles, clothing, shoes and hats " if Sector=="纺织品、服装、鞋帽零售业"
replace Sector = "Electrical equipment manufacturing " if Sector=="电工器械制造业"
replace Sector = "Footwear Sector " if Sector=="制鞋业"
replace Sector = "Electronic Computer Manufacturing " if Sector=="电子计算机制造业"
replace Sector ="Other plastic manufacturing "  if Sector=="其他塑料制造业"
replace Sector = " Dairy Manufacturing" if Sector=="乳制品制造业"
replace Sector = "Metal surface treatment and heat treatment Sector " if Sector=="金属表面处理及热处理业"
replace Sector = "Other transportation equipment manufacturing " if Sector=="其他交通运输设备制造业"
replace Sector = "Container and metal packaging goods manufacturing Sector" if Sector=="集装箱和金属包装物品制造业"
replace Sector = "Foam and artificial leather, synthetic leather manufacturing " if Sector=="泡沫塑料及人造革、合成革制造业"
replace Sector = "Silk spinning Sector " if Sector=="丝绢纺织业"
replace Sector = "Plastic parts manufacturing " if Sector=="塑料零件制造业"
replace Sector = "General machinery manufacturing " if Sector=="普通机械制造业"
replace Sector ="Food Sector "  if Sector=="食品制造业"
replace Sector ="Special machinery and equipment repair Sector"  if Sector=="专用机械设备修理业"
replace Sector =" Other furniture manufacturing"  if Sector=="其他家具制造业"
replace Sector ="Fur tanning and products Sector "  if Sector=="毛皮鞣制及制品业"
replace Sector ="Agriculture, forestry, animal husbandry, fishery and water conservancy machinery manufacturing "  if Sector=="农、林、牧、渔、水利业机械制造业"
replace Sector ="Wooden furniture manufacturing "  if Sector=="木制家具制造业"
replace Sector ="Sporting Goods Manufacturing"  if Sector=="体育用品制造业"
replace Sector ="Other cultural and educational supplies manufacturing"  if Sector=="其他文教用品制造业"
replace Sector ="Shipbuilding Sector"  if Sector=="船舶制造业"
replace Sector ="Wood products Sector "  if Sector=="木制品业"
replace Sector ="Condiment Manufacturing "  if Sector=="调味品制造业"
replace Sector ="Chemical raw materials and chemical products manufacturing " if Sector=="化学原料及化学制品制造业"
replace Sector ="Leather product manufacturing "  if Sector=="皮革制品制造业"
replace Sector ="Pharmaceutical manufacturing "  if Sector=="医药制造业"
replace Sector ="Other mining and dressing services "  if Sector=="其他矿采选服务业"
replace Sector ="Animal medicine manufacturing "  if Sector=="动物用药品制造业"
replace Sector ="Non-ferrous metal smelting and rolling processing Sector "  if Sector=="有色金属冶炼及压延加工业"
replace Sector ="Graphite and carbon products Sector "  if Sector=="石墨及碳素制品业"
replace Sector ="Measuring instrument manufacturing Sector "  if Sector=="计量器具制造业"
replace Sector ="Food processing Sector "  if Sector=="食品加工业"
replace Sector ="Electrical machinery and equipment manufacturing "  if Sector=="电器机械及器材制造业"
replace Sector ="Extractive Services "  if Sector=="采掘服务业"
replace Sector ="Other social services "  if Sector=="其他社会服务业"
replace Sector ="Instrumentation, cultural and office machinery manufacturing "  if Sector=="仪器仪表及文化、办公用机械制造业"
replace Sector ="Electronic components manufacturing "  if Sector=="电子元器件制造业"
replace Sector ="Metal products Sector "  if Sector=="金属制品业"
replace Sector ="Electronic measuring instrument manufacturing "  if Sector=="电子测量仪器制造业"
replace Sector ="Natural crude oil extraction Sector "  if Sector=="天然原油开采业"
replace Sector ="Commercial Brokerage and Agency Sector "  if Sector=="商业经纪与代理业"
replace Sector ="Pulp Manufacturing "  if Sector=="纸浆制造业"
replace Sector ="Cultural and office machinery manufacturing "  if Sector=="文化、办公用机械制造业"
replace Sector ="Plastic wire, rope and woven products manufacturing "  if Sector=="塑料丝、绳及编织品制造业"
replace Sector ="Decoration Sector "  if Sector=="装修装饰业"
replace Sector ="Linen Textile Sector "  if Sector=="麻纺织业"
replace Sector ="Freshwater fisheries "  if Sector=="淡水渔业"
replace Sector ="Gas production Sector "  if Sector=="煤气生产业"
replace Sector ="Ferroalloy Smelting Sector"  if Sector=="铁合金冶炼业"
replace Sector ="Daily-use plastic sundries manufacturing "  if Sector=="日用塑料杂品制造业"
replace Sector ="Communication and cultural industries "  if Sector=="传播与文化产业"
replace Sector ="Rubber manufacturing "  if Sector=="橡胶制造业"
replace Sector = "Bicycle manufacturing " if Sector=="自行车制造业"
replace Sector = "Other communication and cultural service industries " if Sector=="其他传播、文化服务业"
replace Sector = "Communication and related equipment manufacturing " if Sector=="通信及相关设备制造业"
replace Sector = "Cellulose Fiber Manufacturing " if Sector=="纤维素纤维制造业"
replace Sector ="Leather, fur, down and product manufacturing "  if Sector=="皮革、毛皮、羽绒及制品制造业"
replace Sector ="Other civil engineering construction Sector "  if Sector=="其他土木工程建筑业"
replace Sector = "Radar manufacturing " if Sector=="雷达制造业"
replace Sector = "Chemical fiber manufacturing " if Sector=="化学纤维制造业"
replace Sector = "Other auxiliary transportation industries" if Sector=="其他交通运输辅助业"
replace Sector = "Oil and gas extraction Sector " if Sector=="石油和天然气开采业"
replace Sector = "Other majors, scientific research service Sector " if Sector=="其他专业、科研服务业"




//gen hay aval main masoum

gen period = year - 2003
gen stderror = Industy_Code
gen Coverd_ETS_post=c.Covered#c.ETS#c.post 

//Global definition
global dep_var logenvrAEW logNon_envrAEW envrAEW_ratio // broad definition of low carbon
global dep_altvar logenvrAE logenvrAERD  // narrowed defintion of low carbon
global control t_Assets t_Revenue t_ROA t_EBIT t_CurrentLiability // firm-level control variables

//labeling
label variable Coverd_ETS_post "Coverd*ETS*post"
label define ETS 1 "ETS" 0 "Non_ETS"
label values ETS ETS
label define Covered 1 "Covered" 0 "Non_Covered"
label values Covered Covered
label variable Sector   "Name of the firm sector, ex: steel manufacturing sector " 
label variable Industy_Code   "Industrial Classification Codes, classifying industries by a three-digit code" 
label variable t_EBIT   "firm earnings before Interest and taxes" 



//Saving cleaned data
save "main_data.dta",replace






